version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo!
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
    networks:
      - mongo-api-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo-api-network

networks: 
    mongo-api-network:
      driver: bridge